language: python
python:
  - "2.7"
addons:
  ssh_known_hosts: torpedo210.anchor.net.au
before_install:
  - openssl aes-256-cbc -K $encrypted_d4f50cad59d7_key -iv $encrypted_d4f50cad59d7_iv -in .travis/fleetdocsdeploy.enc -out .travis/fleetdocsdeploy -d
install:
  - "pip install -r requirements.txt"
script:
  - "mkdocs build --clean -v"
after_success:
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    chmod 0600 .travis/fleetdocsdeploy;
    rsync -C --delete -va -e 'ssh -i .travis/fleetdocsdeploy' ./site/ fleetdocs@torpedo210.anchor.net.au:/home/fleetdocs/public_html/fleet-magento-1/;
  else
    echo "Not performing a deployment.";
  fi
