language: python
python:
  - "2.7"
addons:
  ssh_known_hosts: sail.anchor.net.au
before_install:
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    openssl aes-256-cbc -K $encrypted_d4f50cad59d7_key -iv $encrypted_d4f50cad59d7_iv -in .travis/fleetdocsdeploy.enc -out .travis/fleetdocsdeploy -d;
  fi;
install:
  - "pip install -r requirements.txt"
script:
  - "mkdocs build --clean -v"
after_success:
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    chmod 0600 .travis/fleetdocsdeploy;
    rsync -C --delete -va -e 'ssh -i .travis/fleetdocsdeploy' ./site/ fleetdocs@sail.anchor.net.au:/home/fleetdocs/public_html/fleet-magento-1/;
  else
    echo "Not performing a deployment.";
  fi
notifications:
  slack:
    rooms:
      - secure: "KJVw2IzoY36JNjdtKsPV9uAfxYGR95zIiX+XmEe9pyotlilNxWke8nDBXYkt5/i+OdA+VaqXUvOqfyU8zGVXE4YwZRsDDtx4Qvjf86aq3GeFFvJRqkiDIZrR5NTYphLhGO3p4rLEXTObEyrB0t9o6C9R4ujjyidV9QmtD8DtNbyL6VUrUT3TO26Kdq8KEKgO7A6LylfsDsoca51F/yVl0DdFrzgLEpILdx4SOWKGfyijyCZE16xi3GkHuAOHaxhgVLfLqMPEeSp/Z8ntkR3h2FF9irkRnoEYEclqkp9evCW+4SOfl+CKakDX9GlSQ0hua9gaX9+95a435ymQr4MG2wYZGp4Sh1BsEmG3nvNIEPmERXrke2Mg3ElaS2KY2dAMquSs+aL039LjC1fE707qhkjCWDQLnqpHvxyqUi08f1Acll1f/F7n1QFv/Q2IW1aw0Wjf6Him4stzKOiuvHsGvb4s5EhzzKXEwFqLrbx/qsTNBUEtka4m7UeDAwHiDHv8fkvH9aOx7mfi8khafrtQO8SDQTUXk0Q3XhFSHKJEBYay19ATzFTEF5k2ho2mdBeA9PdJz7DKtg3zYYgYlY+ajafg11mW0uS6No/7NJjNFL0WDYRPfZjFHjlEB6Ovgs9Xdme4NbwsGY8NP1HFmSkHFTi2fTZdB8JBtVFbYVKuHZ8="
