site_name: Magento on Anchor Fleet
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [extra.js]
google_analytics: ['UA-60495198-2', 'docs.anchorfleet.com']

pages:
- Introduction: 'index.md'
- What is Fleet?: 'what-is-fleet/what-is-fleet.md'
- Configuring Magento for Fleet:
  - 'Introduction': 'configuring-magento-for-fleet/introduction.md'
  - 'Architecture Overview': 'configuring-magento-for-fleet/architecture-overview.md'
  - 'Database Setup': 'configuring-magento-for-fleet/database-setup.md'
  - 'Disable Redirects': 'configuring-magento-for-fleet/disable-redirects.md'
  - 'Configure cache and sessions': 'configuring-magento-for-fleet/configure-cache-and-sessions.md'
  - 'Unset cookie domain': 'configuring-magento-for-fleet/unset-cookie-domain.md'
  - 'Store media in the database': 'configuring-magento-for-fleet/media-in-database.md'
  - 'Configure Varnish': 'configuring-magento-for-fleet/varnish.md'
  - 'Service Hostnames': 'configuring-magento-for-fleet/service-hostnames.md'
  - 'Sending Mail': 'configuring-magento-for-fleet/mail.md'
  - 'Customisation': 'configuring-magento-for-fleet/customisation.md'
  - 'Configuring Solr': 'configuring-magento-for-fleet/solr.md'
  - 'Configuring NFS': 'configuring-magento-for-fleet/nfs.md'
  - 'Health Check': 'configuring-magento-for-fleet/health-check.md'
  - 'Multisite': 'configuring-magento-for-fleet/multisite.md'
  - 'Logging': 'configuring-magento-for-fleet/logging.md'
  - 'Sitemaps': 'configuring-magento-for-fleet/sitemaps.md'
  - 'Going Live': 'configuring-magento-for-fleet/going-live.md'
- Configuring Magento 2 for Fleet (Beta):
  - 'Introduction': 'configuring-magento-2-for-fleet/introduction.md'
  - 'Architecture Overview': 'configuring-magento-2-for-fleet/architecture-overview.md'
  - 'Setup Cron': 'configuring-magento-2-for-fleet/cron.md'
  - 'Database Setup': 'configuring-magento-2-for-fleet/database-setup.md'
  - 'Disable Redirects': 'configuring-magento-2-for-fleet/disable-redirects.md'
  - 'Configure cache and sessions': 'configuring-magento-2-for-fleet/configure-cache-and-sessions.md'
  - 'Unset cookie domain': 'configuring-magento-2-for-fleet/unset-cookie-domain.md'
  - 'Store media in the database': 'configuring-magento-2-for-fleet/media-in-database.md'
  - 'Configure Varnish': 'configuring-magento-2-for-fleet/varnish.md'
  - 'Service Hostnames': 'configuring-magento-2-for-fleet/service-hostnames.md'
  - 'Sending Mail': 'configuring-magento-2-for-fleet/mail.md'
  - 'Customisation': 'configuring-magento-2-for-fleet/customisation.md'
  - 'Configuring NFS': 'configuring-magento-2-for-fleet/nfs.md'
  - 'Health Check': 'configuring-magento-2-for-fleet/health-check.md'
  - 'Multisite': 'configuring-magento-2-for-fleet/multisite.md'
  - 'Logging': 'configuring-magento-2-for-fleet/logging.md'
  - 'Sitemaps': 'configuring-magento-2-for-fleet/sitemaps.md'
  - 'Going Live': 'configuring-magento-2-for-fleet/going-live.md'
- Getting Started:
  - 'Getting Started': 'getting-started/getting-started.md'
  - 'Configuring Revision Control': 'getting-started/configuring-revision-control.md'
  - 'First Deployment': 'getting-started/first-deployment.md'
  - 'Pushing Out a Change': 'getting-started/pushing-a-change.md'
  - 'Cleaning Up Environments': 'getting-started/cleaning-up-environments.md'
  - 'Cleaning Up Releases': 'getting-started/cleaning-up-releases.md'
- How To:
  - 'Manage Environments': 'how-to/manage-environments.md'
  - 'Manage Databases': 'how-to/manage-databases.md'
  - 'Manage Snapshots': 'how-to/manage-snapshots.md'
  - 'Manage IP Whitelists': 'how-to/manage-whitelists.md'
  - 'Manage Log Files': 'how-to/manage-logs.md'
  - 'Manage Notifications': 'how-to/manage-notifications.md'
  - 'Manage Releases': 'how-to/manage-releases.md'
  - 'Manage SSH Keys': 'how-to/manage-keys.md'
  - 'Manage SSL Certificates': 'how-to/manage-certificates.md'
  - 'Manage SQL Scripts': 'how-to/manage-sql-scripts.md'
  - 'Manage Code Repository': 'how-to/manage-code-repository.md'
  - 'Access Inactive Releases': 'how-to/access-inactive-releases.md'
  - 'Configure DNS': 'how-to/configure-dns.md'
  - 'Reporting': 'how-to/access-reports.md'
  - 'Updates': 'how-to/updates.md'
- FAQ:
  - 'Cache and Sessions': 'faq/cache-and-sessions.md'
  - 'Integrations': 'faq/integrations.md'
  - 'Media': 'faq/media.md'
  - 'Monitoring': 'faq/monitoring.md'
  - 'CORS': 'faq/cors.md'
  - 'Software Versions': 'faq/software-versions.md'
  - 'SSL Certificates': 'faq/ssl-certificates.md'
  - 'Performance': 'faq/performance.md'
  - 'Error Pages': 'faq/error-pages.md'
  - 'Updates and Maintenance': 'faq/updates-and-maintenance.md'
- Troubleshooting:
  - 'Magento CMS Images': 'troubleshooting/cms-images.md'
  - 'Database Performance': 'troubleshooting/database.md'
  - 'Database Import Errors': 'troubleshooting/database-import.md'
- Tutorial:
  - 'Introduction': 'tutorial/introduction.md'
  - 'Configuration': 'tutorial/configuration.md'
  - 'Create a release': 'tutorial/create-release.md'
  - 'Staging environment': 'tutorial/staging-environment.md'
  - 'Production environment': 'tutorial/production-environment.md'
- Support: 'support.md'
- Plans: 'plans.md'
- Changelog: 'changelog.md'
